// Generated by CoffeeScript 1.7.1
(function() {
  var manager;

  manager = null;

  window.onresize = function() {
    return manager != null ? typeof manager.handleResize === "function" ? manager.handleResize() : void 0 : void 0;
  };

  window.onload = function() {
    var element, _i, _len, _ref, _results;
    manager = new window.Manager();
    manager.setup();
    manager.handleResize();
    _ref = document.getElementsByTagName('img');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      element = _ref[_i];
      _results.push(element.ondragstart = function(e) {
        return e.preventDefault();
      });
    }
    return _results;
  };

}).call(this);
