// Generated by CoffeeScript 1.7.1
(function() {
  var desktopManager, manager, mobileManager;

  manager = null;

  mobileManager = null;

  desktopManager = null;

  window.onresize = function() {
    if (window.isMobileBrowser() && manager !== mobileManager) {
      manager = mobileManager;
      manager.setup();
    } else if (manager !== desktopManager) {
      manager = desktopManager;
      manager.setup();
    }
    return manager.handleResize();
  };

  window.onload = function() {
    mobileManager = new window.MobileManager();
    desktopManager = new window.DesktopManager();
    return window.onresize();
  };

}).call(this);
