// Generated by CoffeeScript 1.7.1
(function() {
  var Manager;

  Manager = (function() {
    function Manager() {
      this.container = document.getElementById('container');
      this.challenges = [document.getElementById('challenge1'), document.getElementById('challenge2'), document.getElementById('challenge3'), document.getElementById('challenge4')];
      this.submit = document.getElementById('submit');
      this.scoreboard = document.getElementById('scoreboard');
      this.description = document.getElementById('description');
    }

    return Manager;

  })();

  window.Manager = Manager;

}).call(this);
