// Generated by CoffeeScript 1.7.1
(function() {
  var FlipAnimation, MobileManager,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.isMobileBrowser = function() {
    return window.innerWidth < 300 || window.innerHeight < 400;
  };

  FlipAnimation = window.FlipAnimation;

  MobileManager = (function(_super) {
    __extends(MobileManager, _super);

    function MobileManager() {
      MobileManager.__super__.constructor.call(this);
    }

    MobileManager.prototype.setup = function() {
      return this.container.className = 'container-mobile';
    };

    MobileManager.prototype.handleResize = function() {};

    return MobileManager;

  })(window.Manager);

  window.MobileManager = MobileManager;

}).call(this);
